version: '3.7'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
            - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    env_file:
      - db.env
    container_name: db
    
  redis:
    image: redis:alpine
    restart: always

  app:
    container_name: nextcloud
    image: nextcloud:apache
    restart: always
    volumes:
            - /mnt/MAXTOR/nextcloud/:/var/www/html
    environment:
      - VIRTUAL_HOST=www.bluesk.space
      - LETSENCRYPT_HOST=www.bluesk.space
      - LETSENCRYPT_EMAIL=giulio.zani@gmail.com
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default
    
  cron:
    container_name: cron
    image: nextcloud:apache
    restart: always
    volumes:
            - /mnt/MAXTOR/nextcloud/:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  proxy:
    container_name: proxy
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  certs:
  vhost.d:
  html:
  db:

networks:
  proxy-tier:
